name: Plugin A

on:
  workflow_dispatch:
    inputs:
      stateId:
        required: true
      eventName:
        required: true
      event:
        required: true
      settings:
        required: true
      authToken:
        required: true
      ref:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Echo inputs
        run: echo ${{ inputs.settings }}

      - name: Return data
        uses: actions/github-script@v7
        with:
           script: |
             await github.rest.repos.createDispatchEvent({
              owner: "${{ github.repository }}".split("/")[0],
              repo: "${{ github.repository }}".split("/")[1],
              event_type: "return_data_to_kernel",
              client_payload: {
                test_output: "output-plugin-A"
              },
             });

